import { Grid, Typography } from '@material-ui/core';
import SideBar from '../../partial/SideBar/SideBar';
import './Dashboard.scss'

const Dashboard = () => {
    return (
        <Grid container>
            <Grid item md={3} className="sidebar_section">
                <SideBar/>
            </Grid>
            <Grid item md={9}>
                <Typography variant="h2">Dashboard</Typography>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus blanditiis culpa sint aperiam consectetur enim ad! Voluptatum tenetur sunt alias explicabo maxime animi aliquam placeat numquam doloribus vitae asperiores, laudantium distinctio quis! Possimus in ratione iusto natus eius sed aliquam qui fuga mollitia eum, ipsam debitis a necessitatibus dolor quos est, ducimus facere saepe libero vel totam temporibus explicabo? Nisi eius veritatis earum accusantium quos quisquam quas at consectetur eveniet voluptatibus. Ipsum, obcaecati, eos libero earum tempore perspiciatis eius labore sint animi illo totam consequuntur, velit laborum asperiores! Fugit delectus ducimus, ea recusandae sed laudantium! Deserunt mollitia magnam magni blanditiis reiciendis eveniet nobis, a pariatur. Enim accusamus mollitia unde repudiandae voluptate in maiores, distinctio, nam iste corrupti tempore molestiae exercitationem reiciendis. Esse quas recusandae commodi cupiditate natus, error incidunt architecto excepturi provident debitis praesentium minus deleniti odio repellendus aliquid laboriosam enim hic qui maxime sed! Quaerat in praesentium sapiente, ex impedit fuga nesciunt, quod veritatis hic vel provident corrupti error quasi excepturi! Repellendus, quisquam magnam. Nulla sed sunt atque sapiente voluptatem culpa voluptatibus, itaque facilis enim? Quisquam, perspiciatis, temporibus, ducimus delectus odit commodi praesentium reprehenderit eum dicta optio eos! Facilis voluptatum sit quos delectus vero vitae magni temporibus, facere quia explicabo enim architecto inventore cum minus culpa minima reprehenderit voluptas quaerat officiis quam debitis! Reiciendis cum adipisci vitae voluptate distinctio cumque corporis suscipit blanditiis mollitia assumenda, repellendus a dolor rerum quibusdam? Quis, dolore ipsum quaerat cupiditate maxime facere recusandae non! Sed, nulla nobis? Ea sit eum voluptatibus voluptates, sapiente modi atque architecto dolorum ut corrupti minima quasi nesciunt officiis obcaecati ducimus omnis tempore esse sint iste quo mollitia. Dicta natus voluptates neque illum atque doloremque. Saepe exercitationem veniam quibusdam quae voluptatem maiores cupiditate animi vero repudiandae unde, debitis aspernatur sapiente commodi, harum placeat sit consequatur aut. Quam libero ullam rem?</p>

                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore a commodi, ut odit fuga qui veniam itaque minus vel, distinctio, velit quos provident unde officiis facere maiores voluptatum molestias rerum voluptatem natus neque. Rerum velit facilis soluta odio! Ad repellendus velit inventore quo provident in natus ut soluta unde, quaerat aperiam impedit. Fugit repellat vitae maiores asperiores et doloremque id quia numquam quidem autem sunt saepe consequatur, ducimus rem praesentium enim illum magnam esse quasi cupiditate, blanditiis, dolorum beatae suscipit dolore. Suscipit quia delectus repellendus autem, omnis a architecto doloremque ipsam error magnam animi nostrum quam illo odit sequi. Totam eveniet non excepturi, doloribus ullam alias fugiat officiis! Qui fugit neque expedita rerum cum quas maxime hic iusto non laborum labore nisi inventore aspernatur reprehenderit vero facilis consequatur suscipit beatae fugiat, quibusdam incidunt rem. Doloremque debitis veniam assumenda! Ipsa sequi fugit quod quos ipsam, exercitationem id eum beatae. Cumque excepturi sunt praesentium? Qui asperiores architecto accusamus molestias cupiditate fuga. Eligendi voluptatibus in officia placeat quae a alias provident accusamus sit fuga praesentium suscipit repudiandae perferendis culpa, accusantium beatae? Quae sapiente dolores dolorum est non similique porro ab praesentium, quod deleniti sint, nemo quia in veniam ea explicabo omnis doloribus repellendus quas veritatis corporis! Ratione unde sint atque illum, soluta voluptatem. Iure, sint! Ea quam rem ex eius hic sapiente repudiandae, vero laboriosam quidem quas dolore expedita, suscipit impedit! Aliquid quae laboriosam eos molestias molestiae delectus accusantium aperiam temporibus, ut suscipit fugit quis qui vero! Culpa mollitia incidunt omnis repellat, est vero assumenda ab modi esse rerum provident. Recusandae unde nisi nobis maxime. Ipsam laborum voluptas dolorem qui rem quibusdam? Corporis placeat hic modi ex quod esse pariatur necessitatibus dignissimos, labore autem accusamus dolore molestias enim, ratione cum perferendis eligendi rem obcaecati a vitae! Beatae error laboriosam repellat possimus, perspiciatis cupiditate?</p>
            </Grid>
        </Grid>
    );
};

export default Dashboard;